require: rubocop-rails

Rails:
  Enabled: true
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/BracesAroundHashParameters:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/SymbolArray:
  Enabled: false
Style/ModuleFunction:
  Enabled: false
Metrics/MethodLength:
  Max: 20
Layout/LineLength:
  Max: 200
Style/ConditionalAssignment:
  Enabled: false
Metrics/AbcSize:
  Max: 30
