development:
  adapter: postgresql
  host: localhost
  database: ezgolfleague_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  host: localhost
  database: ezgolfleague_test
  pool: 5
  timeout: 5000

staging:
  adapter: postgresql
  host: localhost
  database: ezgolfleague_staging
  username: postgres
  pool: 20

beta:
  adapter: postgresql
  host: 192.168.211.33
  database: ezgolfleague_production
  username: postgres
  pool: 20

production:
  adapter: postgresql
  host: localhost
  database: ezgolfleague_production
  username: postgres
  pool: 20
